# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod ‘Firebase/Analytics’
pod ‘Firebase/Database’

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods


target 'GPTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GPTest

  target 'GPTestTests' do

    inherit! :search_paths
    # Pods for testing
  end

  target 'GPTestUITests' do
    # Pods for testing
  end

end
